# Generated by Django 4.2.4 on 2023-12-19 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deudas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('deudaTotal', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorMensual', models.IntegerField()),
                ('calculoValor', models.IntegerField()),
                ('cantidadCuota', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('finalizada', models.BooleanField()),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorDeuda.deudas')),
            ],
        ),
    ]
